ALTER TABLE public.invitations
  ADD COLUMN IF NOT EXISTS ceremony_program JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS groom_avatar_url TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS bride_avatar_url TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS groom_nickname TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS bride_nickname TEXT NOT NULL DEFAULT '';
